#!/usr/bin/env python3
"""Met à jour 12 racines existantes avec glose Gloton authentique."""
import json
from pathlib import Path

# Pour chaque racine : (entrée Gloton, page, glose_gloton authentique)
# Le glose_gloton cite Gloton littéralement
UPDATES = {
    "ʾ-m-n": ("Gloton, entrée n°66 (p.252)",
        "Gloton ouvre la racine sur un éventail saisissant : <em>« Idée de sécurité, sûreté, confiance, sauvegarde, d'être assuré, d'adhérer, de fidélité, d'ajouter foi, de loyauté, de protection, de croyance. »</em> Le verbe central est défini ainsi : <em>« être en sécurité, avoir confiance, se fier à — contraire de la crainte »</em>. La foi (<em>īmān</em>) n'est donc pas, en arabe, une adhésion mentale à des dogmes : c'est <em>l'état où l'on n'a plus peur</em>. Le croyant est, étymologiquement, celui qui <em>est en sécurité — et qui rend en sécurité</em>. Le dépôt confié (<em>amāna</em>) est l'autre versant de la même intuition : celui à qui Dieu a confié l'existence en garantit la sécurité."),
    "ṣ-d-q": ("Gloton, entrée n°847 (p.495)",
        "Gloton donne pour cette racine une définition qui éclaire d'un coup tout le champ : <em>« Idée d'offrande de soi ou de ses biens en toute spontanéité, sans réserve — Etre vrai, sincère, véridique, authentique, loyal, droit, franc, véritable, réaliser, accomplir, ajouter foi en qqn, reconnaître sans réserve, avoir raison, dire la vérité, dire vrai. »</em> Le nom <em>ṣidq</em> couvre : <em>« vérité, authenticité, véridicité, véracité, loyauté, franchise, droiture, force, vigueur, excellence »</em>. Et — saisissement — le même nom désigne aussi : <em>« offrande spontanée, donation, charité, don, aumône »</em>, et même <em>« dot, donation faite à la femme en vue du mariage »</em>. Dire vrai et donner sans contrepartie partagent la même racine : on se livre entièrement, sans réserve."),
    "ḥ-k-m": ("Gloton, entrée n°349 (p.339)",
        "Gloton donne pour cette racine une définition d'une rare amplitude : <em>« Idée d'établir une règle de sagesse pérenne, d'observer une norme, maintenir une règle, garder dans la voie, accomplir la Loi universelle — Arbitrer, juger, décider, déclarer, déterminer, trancher (un différend), condamner à, consolider, affermir, confirmer, conserver, empêcher de se gâter, administrer, réglementer, normaliser, régler, gouverner, régner, statuer, maîtriser, exercer l'autorité, être savant, être prudent, être d'un jugement solide. »</em> Et il ajoute, image concrète qui éclaire tout le champ : <em>« museler un cheval et lui mettre la martingale sous le menton, maintenir le cap, retenir, contenir et empêcher de faire qqch »</em>. La sagesse arabe est donc, étymologiquement, un <em>mors</em> : ce qui retient, dirige, empêche de se gâter — non un savoir spéculatif, mais une discipline qui tient le cap."),
    "s-l-m": ("Gloton, entrée n°733 (p.458)",
        "Gloton ouvre la racine sur deux sens distincts mais liés : <em>« 1/ piquer qqn (serpent, châtiment), faire une morsure — 2/ Etre sain et sauf, être ou demeurer intact, garder en bon état, se porter bien, échapper, être exempt de. »</em> Le nom couvre : <em>« paix, sécurité, sauvegarde »</em>, et le dérivé <em>islām</em> est défini comme <em>« action de se livrer sain et sauf, captif qui s'est rendu pour garder la vie sauve, paiement anticipé d'une marchandise, obéissance, soumission, qui est sans défaut, intact »</em>. Pour Gloton, l'<em>islām</em> n'est donc pas d'abord une religion : c'est <em>l'acte de se livrer entièrement pour garder la vie sauve</em> — comme le captif qui se rend, comme le marchand qui paie d'avance. Et <em>sullam</em> — l'échelle — est nommée de la même racine : <em>« moyen par lequel on s'échappe, on parvient à qqch »</em>. La paix est l'échelle."),
    "ʿ-r-f": ("Gloton, entrée n°999 (p.547)",
        "Gloton ouvre cette racine sur trois mouvements simultanés : <em>« Idée de connaître en distinguant, en prenant de la hauteur, de se répandre, de se diffuser (parfum), sentir les parfums — Connaître, apprendre, reconnaître et distinguer, discerner, savoir, avouer. »</em> La connaissance arabe, dans cette racine, n'est ni intellectuelle ni signalétique (comme ʿ-l-m) : elle est <em>élévation</em> et <em>diffusion de parfum</em>. On reconnaît en prenant de la hauteur. Le nom <em>ʿurf</em> désigne : <em>« ce que l'on connaît ou reconnaît, usage établi, us et coutumes, droit coutumier, tradition, lieu élevé et reconnu, hauteur, aveu, connaissance »</em>. Et — clé du soufisme — Gloton précise : <em>« les Monts de 'Arafât (de la connaissance), près de La Mekke »</em>. Le sommet où les pèlerins se tiennent est, étymologiquement, le <em>Mont du Connaître</em>."),
    "q-d-s": ("Gloton, entrée n°1212 (p.617)",
        "Gloton donne pour cette racine une définition d'une concision absolue : <em>« Etre pur, sans tache, sans mélange, immaculé, saint. »</em> Le nom <em>quds</em> est : <em>« pureté, sainteté »</em>. Le nom intensif <em>al-Quddūs</em> est : <em>« très saint, très pur — un des Noms de Dieu »</em>. Et le verbe à la forme II : <em>« purifier, sanctifier, proclamer la sainteté, rendre saint, sacraliser, sacrer »</em>. Pour Gloton, la sainteté arabe est donc d'abord une <em>absence de mélange</em> — non un excès de valeur ajoutée, mais une simplicité radicale. Le Saint est ce qui ne se mêle pas, ce qui demeure pur sans réserve."),
    "h-d-y": ("Gloton, entrée n°564 (p.408)",
        "Gloton donne pour cette racine une définition d'une grande simplicité : <em>« Etre bien dirigé, être dans — ou suivre — la bonne direction, être orthodoxe. »</em> Et il précise sur les noms d'action : <em>« direction droite, action droite, marche en ligne droite, droiture, manière d'agir droite »</em>. Le participe actif est <em>« qui dirige bien »</em>, et la forme IV donne <em>hādī</em> : <em>« capable de bien diriger qqn, qui oriente bien, qui est d'un bon conseil »</em>. La guidance, en arabe, est donc une <em>rectitude</em> — une ligne sans déviation. Et le mot <em>hadiyya</em> (cadeau) vient de la même racine : ce qu'on offre pour <em>orienter le cœur</em>."),
    "ḍ-l-l": ("Gloton, entrée n°412 (p.358)",
        "Gloton donne pour cette racine une définition immédiatement concrète : <em>« S'écarter de la route et s'égarer, s'égarer, se perdre, être dépossédé, éprouver ou subir un dommage, s'endommager, avoir le dessous, se tromper dans une affaire de commerce. »</em> Le nom couvre : <em>« mécompte, perte, préjudice, dommage éprouvé, déception »</em>. L'errance arabe n'est donc pas seulement une dérive morale : c'est une <em>perte</em>, un <em>mécompte commercial</em> au sens propre — celui qui s'égare perd quelque chose qu'il avait, et se trouve <em>dépossédé</em>. Sans <em>hudā</em>, on n'erre pas dans le vide : on <em>perd</em>."),
    "z-k-y": ("Gloton, entrée n°635 (p.428)",
        "Gloton donne pour cette racine une définition qui révèle son intuition centrale : <em>« Etre pur, sans tache, croître, grandir, augmenter, convenir à, vivre dans le bien-être, se plaire dans un endroit. »</em> Pureté et croissance — un seul mot pour deux gestes. La <em>zakāt</em> — l'aumône légale — porte exactement cette dualité : en donnant une part de ses biens, on les <em>purifie</em>, et de ce fait ils <em>croissent</em>. Pour Gloton, donc, la purification arabe n'est jamais une simple ablation : c'est une <em>libération de la croissance</em>. Quand l'âme est purifiée, elle ne devient pas plus petite — elle <em>peut enfin grandir</em>."),
    "t-q-y": ("Gloton, entrée n°304 (p.326)",
        "Gloton inscrit cette racine au sens premier de la protection vigilante : <em>« Prendre garde, chercher à éviter, se garder de, craindre, se protéger, être attentif, être vigilant, se méfier, appréhender. »</em> Le nom couvre : <em>« garde, protection, abri, refuge, vigilance »</em>. La <em>taqwā</em> — souvent rendue par « crainte de Dieu » — n'est donc pas une peur paralysante : c'est une <em>vigilance attentive</em>, comme celui qui marche pieds nus dans des ronces et regarde où il pose le pied. Le mot <em>wiqāya</em> (de la même racine) est <em>la protection</em> — ce qu'on interpose entre soi et le danger. La taqwā est cette interposition vigilante."),
    "n-ṣ-r": ("Gloton, entrée n°1518 (p.717)",
        "Gloton décrit cette racine sur l'amplitude de l'aide : <em>« Aider, secourir, assister, défendre qqn, délivrer, donner la victoire, soutenir, seconder, être auxiliaire, donner son appui, arroser abondamment. »</em> Le nom couvre : <em>« assistance, aide, secours, appui, victoire, auxiliaire, soutien, succès, triomphe »</em>. Et — détail remarquable — Gloton note explicitement : <em>« (singulier non coranique = nāṣrānī) chrétien, nazaréen »</em>. Les Chrétiens portent, dans le Coran, le nom de ceux qui ont aidé Jésus — les <em>anṣār</em> de la racine n-ṣ-r. Le secours et la victoire partagent donc leur racine : pour Gloton, on ne triomphe pas seul, on triomphe <em>en aidant et en étant aidé</em>."),
    "w-l-y": ("Gloton, entrée n°1696 (p.772)",
        "Gloton donne pour cette racine un déploiement remarquable : <em>« Etre très proche, contigu, être très près, suivre de très près, toucher à, être à portée de la main, se charger de qqch, être préposé, être l'ami intime de qqn, gouverner, régir, administrer, s'ensuivre, suivre de près, défendre qqn. »</em> Le <em>walī</em> est défini comme : <em>« très proche, immédiat, préposé, ami, protecteur, intime, voisin, contigu, aide, auxiliaire, allié, associé, partisan, maître très proche, compagnon, bienfaiteur, tuteur — un des noms de Dieu »</em>. La sainteté arabe (<em>walāya</em>) est donc, étymologiquement, une <em>contiguïté</em> avec Dieu : le saint est <em>celui qui est à portée de main</em>, celui qui touche au divin. Et — détail capital — la racine porte aussi <em>gouverner, régir, administrer</em> : le walī n'est pas seulement un mystique, c'est aussi un <em>gérant</em>, celui à qui une affaire est confiée."),
}

DICT_PATH = Path(__file__).resolve().parents[1] / "data" / "racines.json"
data = json.loads(DICT_PATH.read_text(encoding="utf-8"))

n = 0
for r in data["racines"]:
    if r["id"] in UPDATES:
        ref, glose = UPDATES[r["id"]]
        r["glose_gloton"] = glose
        r["gloton_ref"] = ref
        n += 1
        print(f"  ✓ {r['id']:>10} → {ref}")

DICT_PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"\n{n} racines révisées.")
