#!/usr/bin/env python3
"""Phase 2 batch 3 : 12 nouvelles racines avec Gloton authentique."""
import json
from pathlib import Path

UPDATES = {
    "q-d-r": ("Gloton, entrée n°1243 (p.628)",
        "Gloton donne pour cette racine un déploiement saisissant qui joint mesure et autorité : <em>« Déterminer, prescrire, décréter, arrêter, décider, juger, ordonner, commander, accomplir, fixer la mesure, avoir pouvoir, être capable, savoir mesurer. »</em> Le nom <em>qadr</em> couvre <em>« mesure, proportion juste, décret, ordre, pouvoir, capacité, valeur, dignité »</em>. Pour Gloton, le <em>qadr</em> n'est jamais arbitraire : c'est <em>la juste mesure</em> de chaque chose. Le décret divin (<em>qadar</em>) n'est pas une fatalité aveugle — c'est l'<em>exact ajustement</em> que Dieu donne à chaque être. La Nuit du Destin (<em>Laylat al-Qadr</em>) tire son nom de la même racine : nuit où la mesure de l'année se décide."),
    "s-m-ʿ": ("Gloton, entrée n°737 (p.460)",
        "Gloton donne pour cette racine une chaîne d'actes qui va de la simple audition jusqu'à l'obéissance : <em>« Ecouter, entendre, ouir, obéir, suivre un avis, comprendre. »</em> Saisissement : en arabe, <em>entendre</em> et <em>obéir</em> partagent leur racine — celui qui écoute vraiment, suit. La formule coranique célèbre <em>samiʿnā wa-aṭaʿnā</em> (« nous avons entendu et nous obéissons », 2, 285) condense la racine : entendre <em>est</em> commencer à obéir. <em>As-Samīʿ</em> — l'Audient — est l'un des Noms divins (n°27 dans la liste canonique) : Dieu n'écoute pas passivement ; Sa présence à l'écoute est déjà un acte."),
    "kh-l-q": ("Gloton, entrée n°437 (p.367)",
        "Gloton ouvre cette racine sur un geste artisanal : <em>« Donner la mesure à, les proportions ou la norme à ; prendre la mesure (sans couper) ; tailler ; façonner ; créer en donnant forme. »</em> Pour Gloton, la création arabe n'est pas un acte ex nihilo abstrait — c'est <em>donner la mesure</em>, façonner avec proportion. Et — détail capital — la même racine donne <em>khulq</em> : <em>« caractère, mœurs, disposition naturelle »</em>. Le caractère d'une personne (akhlāq) est, étymologiquement, ce qui a été <em>créé en elle</em>, sa <em>forme intérieure</em>. Pour le soufi, donc, travailler son caractère et participer à la création divine sont une seule discipline."),
    "s-b-ḥ": ("Gloton, entrée n°664 (p.437)",
        "Gloton donne pour cette racine une intuition saisissante : <em>« Nager, baigner, se mouvoir comme si on nageait, évoluer, marcher avec rapidité, exalter qqn, être exempt de tout défaut. »</em> La glorification arabe (<em>tasbīḥ</em>) est donc, étymologiquement, un <em>mouvement de nage</em> : on glisse loin de tout ce qui rabaisse Dieu. Dire <em>subḥān Allāh</em>, ce n'est pas seulement « gloire à Dieu » — c'est <em>« je nage loin de toute imperfection que je pourrais Lui attribuer »</em>. Le <em>tanzīh</em> (transcendance) classique du soufisme prend ici sa source : transcender, c'est faire <em>nager</em> Dieu hors des images humaines."),
    "ʿ-d-l": ("Gloton, entrée n°988 (p.542)",
        "Gloton donne pour cette racine une définition d'amplitude juridique et métaphysique : <em>« Etre juste, prononcer avec justice, décider en toute justice, égaliser, être équivalent, traiter avec équité, équilibrer, ajuster. »</em> Le nom <em>ʿadl</em> couvre <em>« justice, équité, équilibre, ajustement, ce qui pèse également »</em>. Pour Gloton, la justice arabe est avant tout un <em>équilibre des deux plateaux</em> — non un verdict moral abstrait mais une <em>balance</em>. Et — remarquable — la racine donne aussi le verbe <em>« s'écarter, dévier »</em> dans son antonyme : <em>ḍ-l-l</em> est précisément la déviation de l'équilibre ʿ-d-l."),
    "g-f-r": ("Gloton, entrée n°1098 (p.579)",
        "Gloton donne pour cette racine une définition d'une justesse parfaite : <em>« Couvrir, recouvrir (les fautes, les péchés), ne plus les laisser paraître, cacher, receler. »</em> Le pardon arabe (<em>maghfira</em>) n'est donc pas un effacement — c'est une <em>couverture</em>. Le mot <em>maghfir</em> désigne d'ailleurs le <em>casque</em> qui protège la tête au combat : ce qui couvre vraiment. Quand le serviteur demande <em>ighfir lī</em>, il ne demande pas que Dieu fasse comme si la faute n'avait pas eu lieu — il demande qu'Il <em>couvre</em> la faute, la voile, la rende invisible. <em>Al-Ghafūr</em> (le Très-Recouvreur) est le Nom divin qui en porte la plénitude."),
    "kh-y-r": ("Gloton, entrée n°455 (p.372)",
        "Gloton donne pour cette racine une définition qui joint la qualité et le choix : <em>« Obtenir qqch de bon, de bien ; être favorable, propice ; préférer, choisir, donner la préférence à. »</em> Le nom <em>khayr</em> couvre <em>« le bien, le bon, la richesse, l'excellence, ce qu'on choisirait »</em>. Pour Gloton, choisir et obtenir le bon partagent leur racine : <em>choisir vraiment, c'est choisir ce qui est bon</em>. L'<em>ikhtiyār</em> (libre choix) est donc, étymologiquement, le choix du bien. Et la formule coranique récurrente <em>khayr lakum</em> (« meilleur pour vous ») rappelle que Dieu choisit pour Son serviteur ce qui est bon — même quand le serviteur préférerait autre chose."),
    "ḥ-y-y": ("Gloton, entrée n°387 (p.349)",
        "Gloton donne pour cette racine une définition d'une concision étonnante : <em>« Vivre, rougir, avoir honte. »</em> Trois sens en trois mots — et leur lien est philosophiquement profond. Vivre, en arabe, c'est avoir la capacité de <em>rougir</em>, c'est-à-dire d'être conscient du regard de l'autre. Le mort n'a pas honte parce qu'il ne sent plus le regard. <em>Al-Ḥayy</em> (le Vivant) est l'un des Noms divins ; et <em>al-ḥayāʾ</em> (la pudeur, la honte révérencielle) est, dans le hadith, <em>« une branche de la foi »</em>. Pour Gloton, donc, être vivant et être capable de rougir devant Dieu sont, étymologiquement, le même état."),
    "m-w-t": ("Gloton, entrée n°1464 (p.699)",
        "Gloton donne pour cette racine une chaîne descendante saisissante : <em>« finir, s'éteindre, périr, cesser de vivre, succomber, rendre l'âme, trépasser, se calmer (vent). »</em> Et — détail révélateur — il note que la même racine s'applique au <em>vent qui se calme</em>. Mourir, en arabe, c'est <em>se calmer comme un vent</em> : le souffle (nafas) qui passait par soi cesse de passer. Le Nom <em>al-Mumīt</em> (Celui qui fait mourir) descend de cette racine : Dieu ne tue pas violemment dans le langage coranique — Il <em>fait cesser</em>. La mort est donc, pour Gloton, l'<em>apaisement final du souffle</em>."),
    "q-w-l": ("Gloton, entrée n°1195 (p.610)",
        "Gloton donne pour cette racine la définition la plus large possible de la parole : <em>« Prononcer (un mot, un discours), parler, proférer, adresser la parole à qqn, avoir une grande bouche, communiquer par la voix. »</em> Le nom <em>qawl</em> est <em>« parole, dire, propos, déclaration, énoncé »</em>. Et — détail capital — la même racine donne le verbe d'imitation <em>qāla</em> (« il dit »), le plus fréquent du Coran. Pour Gloton, le <em>qawl</em> coranique englobe tout ce qui sort de la bouche : la parole vraie, la parole vide, la médisance — d'où la responsabilité particulière de la langue dans le soufisme classique."),
    "n-z-l": ("Gloton, entrée n°1581 (p.737)",
        "Gloton ouvre cette racine sur un mouvement de descente concret : <em>« Rouler et tomber en bas, baisser, s'abaisser, décliner, diminuer, décroître, tomber, descendre, mettre pied à terre, précipiter en bas, amoindrir, s'abattre. »</em> Et — saisissement — la même racine donne <em>« faire descendre, faire venir d'en haut »</em>. La <em>descente du Coran</em> (<em>tanzīl al-Qurʾān</em>) est dite par cette racine : non un simple envoi, mais une <em>chute graduée</em> du ciel vers la terre. Et <em>manzil</em> (étape, demeure provisoire) en vient aussi : c'est l'endroit où l'on <em>met pied à terre</em>. Le voyageur soufi marche d'un manzil à l'autre."),
    "ʿ-q-l": ("Gloton, entrée n°1036 (p.559)",
        "Gloton donne pour cette racine la genèse étonnante de l'intellect arabe : <em>« Attacher, retenir, lier, joindre, ligaturer, entraver, resserrer, faire le lien, lier les idées entre elles, comprendre, connaître, concevoir, faire preuve d'intelligence, de discernement. »</em> Le verbe ʿaqala désigne d'abord, concrètement, <em>l'action de lier le chameau avec une entrave</em> (ʿiqāl). De ce geste vient le nom de l'intelligence : <em>ʿaql</em> = ce qui lie. Comprendre, en arabe, c'est <em>relier</em>. Pour Gloton, donc, l'intelligence n'est pas une faculté abstraite — c'est l'<em>entrave qui empêche la nafs de divaguer</em>. Le formule coranique <em>la-ʿallakum taʿqilūn</em> (« peut-être lierez-vous ») est répétée pour inviter le lecteur à <em>faire le lien</em> entre les signes."),
}

DICT_PATH = Path(__file__).resolve().parents[1] / "data" / "racines.json"
data = json.loads(DICT_PATH.read_text(encoding="utf-8"))
n = 0
for r in data["racines"]:
    if r["id"] in UPDATES:
        ref, glose = UPDATES[r["id"]]
        r["glose_gloton"] = glose
        r["gloton_ref"] = ref
        n += 1
        print(f"  ✓ {r['id']:>10} → {ref}")
DICT_PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"\n{n} racines révisées.")
