#!/usr/bin/env python3
"""Phase 2 batch 2 : met à jour 15 racines avec glose Gloton authentique."""
import json
from pathlib import Path

UPDATES = {
    "ʾ-l-h": ("Gloton, entrée n°55 (p.248)",
        "Gloton note d'emblée le rang de cette racine : <em>« Racine formant les noms Allâh et Ilâh — Adorer en tant que Dieu (ou dieu) — être dans la stupéfaction de Sa contemplation. »</em> Le nom <em>ilāh</em> désigne <em>« Dieu digne d'adoration, dieu qu'on adore »</em>. Gloton précise que le terme arabe s'applique aussi bien au vrai Dieu qu'aux faux dieux : c'est l'<em>adoration</em> qui constitue la divinité, étymologiquement. <em>Allāh</em> est donc, dans cette racine, <em>l'Adoré par excellence</em> — Celui devant qui le cœur reste stupéfait."),
    "ʾ-ḥ-d": ("Gloton, entrée n°1640 (p.754) — sous racine w-ḥ-d",
        "Gloton place <em>aḥad</em> dans la même racine que <em>wāḥid</em> (w-ḥ-d) : <em>« Etre unique, seul, solitaire, singulier, sans pareil, isolé, séparé, identique à. »</em> Le mot <em>aḥad</em> est encore plus radical que <em>wāḥid</em> : il refuse toute composition, toute partition. La sourate 112 commence par <em>Qul huwa Llāhu Aḥad</em> — « Dis : Il est Dieu, Un » — où <em>Aḥad</em> dit l'unicité absolue, sans partage possible. Pour Gloton, <em>aḥad</em> est l'attestation que Dieu n'est pas un parmi plusieurs : Il est <em>seul à pouvoir dire « Je »</em>."),
    "w-ḥ-d": ("Gloton, entrée n°1640 (p.754)",
        "Gloton donne pour cette racine une définition d'amplitude métaphysique : <em>« Etre unique, seul, solitaire, singulier, sans pareil, isolé, séparé, identique à. »</em> Les dérivés couvrent : <em>« unicité, unité, l'un, le seul, isolé »</em>, puis vers les formes verbales : <em>« faire un, unifier, déclarer l'unicité, reconnaître la singularité absolue »</em>. C'est cette dernière forme qui donne <em>tawḥīd</em> : <em>« proclamation de l'unicité divine, attestation que Dieu est Un »</em>. Pour Gloton, le tawḥīd n'est donc pas une thèse théorique sur Dieu — c'est l'acte par lequel le serviteur <em>fait l'unité</em> dans son propre regard, refusant d'associer quoi que ce soit à l'Un."),
    "ḥ-m-d": ("Gloton, entrée n°359 (p.342)",
        "Gloton donne pour cette racine une définition saisissante en sa simplicité : <em>« Louer, louanger, glorifier, remercier, approuver, rendre grâce, trouver qqn digne d'éloges, proclamer les qualités de qqn. »</em> Le nom <em>ḥamd</em> couvre : <em>« louange, action de grâce, proclamation des perfections, gloire reconnue »</em>. Et — note clé — Gloton souligne que la <em>ḥamd</em> diffère du <em>shukr</em> (gratitude) : on remercie pour ce qu'on a reçu (shukr), on loue pour ce que l'autre <em>est</em> (ḥamd). Dire <em>al-ḥamdu li-Llāh</em>, ce n'est donc pas remercier Dieu pour un bienfait précis — c'est proclamer Sa perfection, qu'on en bénéficie ou non. <em>Muḥammad</em> (le très loué) et <em>Aḥmad</em> (le plus louangeur) descendent de cette même racine."),
    "ṣ-l-w": ("Gloton, entrée n°874 (p.504)",
        "Gloton ouvre cette racine sur une intuition concrète et inattendue : <em>« Idée d'arriver derrière qqn et de le rattraper — Toucher, atteindre, blesser qqn au dos. »</em> La prière (<em>ṣalāt</em>) descend donc, étymologiquement, du geste de <em>rattraper celui qui marche devant</em>. Et Gloton cite explicitement le verset 33, 56 : <em>« Certes, Allâh et Ses anges effectuent la liaison de grâce avec (ou = prient sur) le Prophète. »</em> La prière soufie est précisément cela : une <em>liaison de grâce</em> où le serviteur rattrape, par la verticale, Celui qui le précède éternellement. Le mot apparenté <em>ṣilā</em> (lien) confirme l'intuition — la prière est un lien."),
    "f-h-m": ("Gloton, entrée n°1187 (p.608)",
        "Gloton donne pour cette racine une définition d'apparente simplicité : <em>« Comprendre, entendre, saisir par l'intelligence, concevoir, saisir le sens, interpréter. »</em> Et il distingue la forme IV : <em>« Faire comprendre, saisir ou savoir, rendre intelligible. »</em> Pour Gloton, <em>fahm</em> est la compréhension <em>directe</em> du sens — différente de <em>ʿaql</em> (qui lie les concepts), de <em>fikr</em> (qui pèse et retourne), et de <em>maʿrifa</em> (qui reconnaît par parfum). Le <em>fahm</em>, c'est <em>la lumière qui se fait dans l'esprit</em> quand le sens se livre."),
    "f-k-r": ("Gloton, entrée n°1177 (p.606)",
        "Gloton donne pour cette racine un déploiement complet de la pensée discursive : <em>« Penser, réfléchir, méditer, raisonner, cogiter, délibérer, spéculer, considérer. »</em> Le nom <em>fikr</em> est <em>« pensée, réflexion, méditation, considération »</em>. Pour Gloton, la <em>fikr</em> est l'opération mentale par laquelle on <em>pèse et retourne</em> une idée — différente du <em>fahm</em> (saisie directe) et du <em>ʿaql</em> (intellect qui lie). Le <em>tafakkur</em> coranique (méditation soufie sur les signes) descend de cette racine : non un raisonnement spéculatif, mais une rumination patiente qui laisse le sens se déposer."),
    "j-h-d": ("Gloton, entrée n°272 (p.315)",
        "Gloton donne pour cette racine la définition la plus exacte : <em>« S'efforcer, s'appliquer, insister, travailler avec zèle et assiduité, faire un effort en vue de. »</em> Et il cite directement le verset coranique : <em>« N'obéis donc pas à ceux qui rejettent la foi et par ceci lutte contre eux avec une grande vigueur ! »</em> Mais — point essentiel — la lutte (<em>jihād</em>) en arabe n'est pas d'abord guerre : c'est <em>l'effort déployé</em>, le travail acharné. Le hadith célèbre dit : <em>« Nous sommes revenus du petit jihād (la bataille) au grand jihād (le combat contre la nafs). »</em> Pour Gloton, donc, le jihād est d'abord intérieur — l'effort soutenu de la voie."),
    "gh-y-b": ("Gloton, entrée n°1120 (p.586)",
        "Gloton donne pour cette racine une définition précise et brève : <em>« Etre absent, caché, loin de, invisible, mystérieux. »</em> Le nom <em>ghayb</em> couvre <em>« mystère, ce qui est invisible, l'inattesté, le caché »</em>. Pour Gloton, le <em>ghayb</em> coranique n'est pas un secret à percer — c'est, structurellement, ce qui demeure caché à la créature. Les croyants sont définis dès la deuxième sourate (2, 3) comme <em>« ceux qui portent la foi au ghayb »</em> : faire confiance à ce qu'on ne voit pas, et qu'on ne verra peut-être jamais. Et <em>ʿālam al-ghayb</em> (le monde du Mystère) s'oppose à <em>ʿālam al-shahāda</em> (le monde du visible)."),
    "w-j-h": ("Gloton, entrée n°1639 (p.754)",
        "Gloton ouvre la racine sur le sens premier, concret : <em>« Toucher, frapper ou blesser au visage, surpasser qqn en dignité, en rang, en considération. »</em> Le nom <em>wajh</em> est <em>« visage, face, côté, direction, aspect »</em>. Et — saisissement — la racine donne aussi le verbe <em>tawajjaha</em> : <em>tourner sa face vers</em>. Le visage et l'orientation partagent donc leur racine. Le verset central est dans Ibrāhīm : <em>« J'ai tourné ma face (wajhī) vers Celui qui a créé les cieux et la terre »</em> (6, 79). Pour Gloton, le visage n'est pas un trait identitaire — c'est <em>la direction que prend l'être</em>, sa face exposée à Dieu."),
    "kh-l-d": ("Gloton, entrée n°698 (p.448)",
        "Gloton donne pour cette racine une définition d'une rare densité métaphysique : <em>« Idée d'éternité, de non fin dans le temps, de permanence. »</em> Le nom <em>khulūd</em> est <em>« éternité, perpétuité, immortalité, le fait de demeurer sans terme »</em>. Et le participe <em>khālid</em> couvre <em>« éternel, perpétuel, sans fin »</em>. Pour Gloton, le <em>khulūd</em> coranique ne désigne pas l'éternité divine (qui est intemporelle) mais l'éternité <em>relative</em> — celle où la créature demeure dans l'état où elle s'est fixée, sans plus en sortir. Le Paradis (<em>jannāt al-khuld</em>) est <em>la Demeure de la Permanence</em> : non parce que le temps y est aboli, mais parce que rien n'y est jamais perdu."),
    "b-y-n": ("Gloton, entrée n°126 (p.271)",
        "Gloton donne pour cette racine un double sens remarquable : <em>« Voir clair, regarder, saisir intuitivement, être clairvoyant, comprendre. »</em> Mais aussi : <em>« Etre clair, manifeste, évident, distinct, séparé. »</em> La racine porte ainsi à la fois <em>l'acte de voir clair</em> et <em>l'état de ce qui est clair</em>. Le nom <em>bayān</em> est <em>« exposition claire, démonstration, élucidation »</em>. Et le mot <em>bayna</em> (entre) descend de la même racine — ce qui sépare et fait voir. Pour Gloton, donc, voir clair (<em>tabayyana</em>) et être clair (<em>bāna</em>) sont les deux faces d'un même acte : la clarté qui se manifeste éclaire, et la clarté qu'on perçoit révèle."),
    "ʿ-r-j": ("Gloton, entrée n°857 (p.499)",
        "Gloton donne pour cette racine une définition d'une concrétude saisissante : <em>« Monter par degrés, monter sur une échelle, se déplacer progressivement, gravir (une pente). »</em> Le nom <em>miʿrāj</em> est <em>« l'échelle, le moyen d'ascension »</em>. Pour Gloton, l'<em>ascension</em> arabe n'est jamais un envol soudain : c'est un mouvement <em>par degrés</em>, une élévation graduée. Le <em>Miʿrāj</em> du Prophète (son ascension nocturne) n'est donc pas un saut hors du monde — c'est une <em>échelle</em> qu'il gravit. Tout cheminement spirituel partage cette structure échellisée : on monte d'un degré à la fois, et chaque marche tient sur celle d'en dessous."),
    "k-t-b": ("Gloton, entrée n°701 (p.449)",
        "Gloton donne pour cette racine un déploiement saisissant : <em>« Ecrire, couper, renverser (à terre), composer un livre, tracer des lignes ou des caractères, prescrire, ordonner, décréter, fixer par écrit, condamner, destiner. »</em> Et le nom <em>kitāb</em> couvre <em>« livre, écriture, écrit, lettre, message, prescription, décret, destinée »</em>. Pour Gloton, écrire n'est jamais un acte neutre : c'est <em>fixer</em>, <em>décréter</em>, parfois <em>condamner</em>. Quand le Coran parle d'un <em>kitāb</em>, ce n'est jamais seulement un livre — c'est aussi le <em>décret divin</em> qui inscrit l'existence. Et la racine évoque, étonnamment, l'idée de <em>couper</em> : l'écriture tranche, sépare, fixe ce qui ne reviendra pas."),
    "r-b-b": ("Gloton, entrée n°531 (p.396)",
        "Gloton ouvre cette racine sur deux gestes inséparables : <em>« Idée de maîtriser et d'éduquer — être maître, chef, seigneur ; avoir le contrôle de, exercer l'autorité ; élever, instruire, éduquer, faire grandir progressivement, faire mûrir. »</em> Le nom <em>rabb</em> est donc <em>à la fois maître et éducateur</em>. C'est ce double sens qui rend la traduction par « Seigneur » insuffisante. Le verset central de la Fātiḥa — <em>al-ḥamdu li-Llāhi Rabbi-l-ʿālamīn</em> — devrait s'entendre comme : <em>la louange est pour Dieu, l'Éducateur des mondes</em>. Pour Gloton, le Rabb n'écrase pas Sa créature : Il la <em>fait grandir</em>, comme un précepteur fait grandir l'enfant."),
}

DICT_PATH = Path(__file__).resolve().parents[1] / "data" / "racines.json"
data = json.loads(DICT_PATH.read_text(encoding="utf-8"))

n = 0
for r in data["racines"]:
    if r["id"] in UPDATES:
        ref, glose = UPDATES[r["id"]]
        r["glose_gloton"] = glose
        r["gloton_ref"] = ref
        n += 1
        print(f"  ✓ {r['id']:>10} → {ref}")

DICT_PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"\n{n} racines révisées.")
